import type {
  KPIData,
  RevenueDataPoint,
  Product,
  Order,
  Customer,
  Integration,
  AdCampaign,
  PaymentSettlement,
  ForecastDataPoint,
  ProfitBreakdown,
  TeamMember,
  PricingPlan,
  NavItem,
  ChatConversation
} from "../types";

// ─── Dashboard KPIs ─────────────────────────────────────────
export const dashboardKPIs: KPIData[] = [
  {
    label: "Total Revenue",
    value: 2847500,
    change: 12.5,
    changeLabel: "vs last month",
    format: "currency",
    sparklineData: [1850, 2100, 1920, 2350, 2180, 2540, 2420, 2650, 2780, 2847],
  },
  {
    label: "Net Profit",
    value: 854250,
    change: 8.3,
    changeLabel: "vs last month",
    format: "currency",
    sparklineData: [520, 610, 580, 690, 640, 730, 710, 780, 820, 854],
  },
  {
    label: "Total Orders",
    value: 1247,
    change: 15.2,
    changeLabel: "vs last month",
    format: "number",
    sparklineData: [810, 920, 870, 1020, 960, 1100, 1050, 1150, 1200, 1247],
  },
  {
    label: "Avg Order Value",
    value: 2283,
    change: -2.1,
    changeLabel: "vs last month",
    format: "currency",
    sparklineData: [2350, 2280, 2320, 2310, 2290, 2270, 2300, 2260, 2290, 2283],
  },
];

// ─── Revenue Chart Data ─────────────────────────────────────
export const revenueData: RevenueDataPoint[] = [
  { month: "Jan", revenue: 1850000, profit: 555000, orders: 810, adSpend: 185000 },
  { month: "Feb", revenue: 2100000, profit: 630000, orders: 920, adSpend: 210000 },
  { month: "Mar", revenue: 1920000, profit: 576000, orders: 870, adSpend: 192000 },
  { month: "Apr", revenue: 2350000, profit: 705000, orders: 1020, adSpend: 235000 },
  { month: "May", revenue: 2180000, profit: 654000, orders: 960, adSpend: 218000 },
  { month: "Jun", revenue: 2540000, profit: 762000, orders: 1100, adSpend: 254000 },
  { month: "Jul", revenue: 2420000, profit: 726000, orders: 1050, adSpend: 242000 },
  { month: "Aug", revenue: 2650000, profit: 795000, orders: 1150, adSpend: 265000 },
  { month: "Sep", revenue: 2780000, profit: 834000, orders: 1200, adSpend: 278000 },
  { month: "Oct", revenue: 2847500, profit: 854250, orders: 1247, adSpend: 284750 },
  { month: "Nov", revenue: 3100000, profit: 930000, orders: 1350, adSpend: 310000 },
  { month: "Dec", revenue: 3450000, profit: 1035000, orders: 1500, adSpend: 345000 },
];

// ─── Profit Breakdown ───────────────────────────────────────
export const profitBreakdown: ProfitBreakdown[] = [
  { label: "Revenue", value: 2847500, color: "#6366f1", percentage: 100 },
  { label: "COGS", value: -1138000, color: "#ef4444", percentage: 40 },
  { label: "Ad Spend", value: -284750, color: "#f59e0b", percentage: 10 },
  { label: "Shipping", value: -284750, color: "#3b82f6", percentage: 10 },
  { label: "Gateway Fees", value: -56950, color: "#8b5cf6", percentage: 2 },
  { label: "Refunds", value: -228800, color: "#ec4899", percentage: 8 },
  { label: "Net Profit", value: 854250, color: "#10b981", percentage: 30 },
];

// ─── Products ───────────────────────────────────────────────
export const products: Product[] = [
  {
    id: "PRD001",
    name: "Organic Vitamin C Serum",
    sku: "BEA-001",
    price: 899,
    cost: 210,
    category: "Beauty",
    stock: 342,
    sold: 1250,
    revenue: 1123750,
    profit: 861250,
    margin: 76.6,
    status: "active",
  },
  {
    id: "PRD002",
    name: "Ayurvedic Hair Oil",
    sku: "BEA-002",
    price: 599,
    cost: 130,
    category: "Beauty",
    stock: 512,
    sold: 2100,
    revenue: 1257900,
    profit: 984900,
    margin: 78.2,
    status: "active",
  },
  {
    id: "PRD003",
    name: "Wireless Earbuds Pro X",
    sku: "ELE-003",
    price: 2499,
    cost: 1100,
    category: "Electronics",
    stock: 89,
    sold: 620,
    revenue: 1549380,
    profit: 867380,
    margin: 56.0,
    status: "active",
  },
  {
    id: "PRD004",
    name: "Smart Fitness Band V2",
    sku: "ELE-004",
    price: 1999,
    cost: 950,
    category: "Electronics",
    stock: 0,
    sold: 480,
    revenue: 959520,
    profit: 503520,
    margin: 52.5,
    status: "active",
  },
  {
    id: "PRD005",
    name: "Organic Green Tea Capsules",
    sku: "HEA-005",
    price: 499,
    cost: 111,
    category: "Health",
    stock: 1205,
    sold: 1780,
    revenue: 888220,
    profit: 690620,
    margin: 77.7,
    status: "active",
  },
];

// ─── Orders ─────────────────────────────────────────────────
export const orders: Order[] = [
  {
    id: "ORD-10248",
    customer: "Rohan Sharma",
    email: "rohan@gmail.com",
    date: new Date(Date.now() - 5 * 60000).toISOString(),
    total: 2499,
    subtotal: 2499,
    shipping: 100,
    tax: 0,
    discount: 0,
    items: 1,
    status: "delivered",
    paymentMethod: "UPI",
    profit: 1399,
    channel: "Shopify",
  },
  {
    id: "ORD-10247",
    customer: "Priya Patel",
    email: "priya.p@yahoo.com",
    date: new Date(Date.now() - 15 * 60000).toISOString(),
    total: 899,
    subtotal: 899,
    shipping: 50,
    tax: 0,
    discount: 0,
    items: 1,
    status: "delivered",
    paymentMethod: "Razorpay",
    profit: 689,
    channel: "Shopify",
  },
  {
    id: "ORD-10246",
    customer: "Anil Kapoor",
    email: "anil@kapoor.co",
    date: new Date(Date.now() - 45 * 60000).toISOString(),
    total: 3598,
    subtotal: 3598,
    shipping: 0,
    tax: 0,
    discount: 400,
    items: 2,
    status: "processing",
    paymentMethod: "Credit Card",
    profit: 1898,
    channel: "Shopify",
  },
  {
    id: "ORD-10245",
    customer: "Meera Joshi",
    email: "meera.j@gmail.com",
    date: new Date(Date.now() - 120 * 60000).toISOString(),
    total: 1999,
    subtotal: 1999,
    shipping: 100,
    tax: 0,
    discount: 0,
    items: 1,
    status: "shipped",
    paymentMethod: "COD",
    profit: 1049,
    channel: "Shopify",
  },
  {
    id: "ORD-10244",
    customer: "Vikram Malhotra",
    email: "vikram@outlook.com",
    date: new Date(Date.now() - 360 * 60000).toISOString(),
    total: 599,
    subtotal: 599,
    shipping: 80,
    tax: 0,
    discount: 0,
    items: 1,
    status: "pending",
    paymentMethod: "UPI",
    profit: 469,
    channel: "Shopify",
  },
  {
    id: "ORD-10243",
    customer: "Karan Johar",
    email: "karan@dharma.in",
    date: new Date(Date.now() - 720 * 60000).toISOString(),
    total: 1198,
    subtotal: 1198,
    shipping: 0,
    tax: 0,
    discount: 100,
    items: 2,
    status: "cancelled",
    paymentMethod: "UPI",
    profit: 0,
    channel: "Shopify",
  },
  {
    id: "ORD-10242",
    customer: "Siddharth Roy",
    email: "sid.roy@gmail.com",
    date: new Date(Date.now() - 1440 * 60000).toISOString(),
    total: 2499,
    subtotal: 2499,
    shipping: 100,
    tax: 0,
    discount: 0,
    items: 1,
    status: "refunded",
    paymentMethod: "Debit Card",
    profit: -1100,
    channel: "Shopify",
  },
];

// ─── Customers ──────────────────────────────────────────────
export const customers: Customer[] = [
  {
    id: "CST001",
    name: "Rohan Sharma",
    email: "rohan@gmail.com",
    phone: "+91 98765 43210",
    totalOrders: 5,
    totalSpent: 12495,
    ltv: 12495,
    lastOrder: "2024-10-15",
    city: "Mumbai",
    segment: "vip",
  },
  {
    id: "CST002",
    name: "Priya Patel",
    email: "priya.p@yahoo.com",
    phone: "+91 87654 32109",
    totalOrders: 3,
    totalSpent: 2697,
    ltv: 2697,
    lastOrder: "2024-10-15",
    city: "Ahmedabad",
    segment: "regular",
  },
  {
    id: "CST003",
    name: "Anil Kapoor",
    email: "anil@kapoor.co",
    phone: "+91 76543 21098",
    totalOrders: 8,
    totalSpent: 28784,
    ltv: 28784,
    lastOrder: "2024-10-15",
    city: "Delhi",
    segment: "vip",
  },
  {
    id: "CST004",
    name: "Meera Joshi",
    email: "meera.j@gmail.com",
    phone: "+91 65432 10987",
    totalOrders: 1,
    totalSpent: 1999,
    ltv: 1999,
    lastOrder: "2024-10-15",
    city: "Pune",
    segment: "new",
  },
  {
    id: "CST005",
    name: "Vikram Malhotra",
    email: "vikram@outlook.com",
    phone: "+91 54321 09876",
    totalOrders: 2,
    totalSpent: 1198,
    ltv: 1198,
    lastOrder: "2024-10-15",
    city: "Bangalore",
    segment: "at-risk",
  },
];

// ─── Integrations ───────────────────────────────────────────
export const integrations: Integration[] = [
  {
    id: "INT001",
    name: "Shopify",
    description: "Sync orders, products, customers, and fulfillment statuses.",
    icon: "ShoppingBag",
    status: "connected",
    phase: 1,
    lastSync: "5 mins ago",
    category: "ecommerce",
    features: ["Real-time Sync", "Multi-store support", "Fulfillment updates"],
  },
  {
    id: "INT002",
    name: "Meta Ads",
    description: "Attribute campaigns, impressions, and ad spend MoM.",
    icon: "Megaphone",
    status: "connected",
    phase: 1,
    lastSync: "30 mins ago",
    category: "ads",
    features: ["Spend tracking", "Campaign ROAS analytics", "CPA breakdown"],
  },
  {
    id: "INT003",
    name: "Google Ads",
    description: "Track search and shopping campaign attribution.",
    icon: "Megaphone",
    status: "connected",
    phase: 1,
    lastSync: "1 hour ago",
    category: "ads",
    features: ["ROAS tracking", "PMax campaign attribution", "Keyword cost insights"],
  },
  {
    id: "INT004",
    name: "Shiprocket",
    description: "Import shipping costs, courier fees, and track RTO rates.",
    icon: "Truck",
    status: "connected",
    phase: 2,
    lastSync: "2 hours ago",
    category: "shipping",
    features: ["Automatic RTO alerts", "Courier performance comparison", "Cod charges sync"],
  },
  {
    id: "INT005",
    name: "Razorpay",
    description: "Sync payment settlements, fee distributions, and UPI rates.",
    icon: "CreditCard",
    status: "connected",
    phase: 2,
    lastSync: "4 hours ago",
    category: "payments",
    features: ["Gateway fees tracking", "UPI vs Card breakdown", "Settlement timing alerts"],
  },
];

// ─── Preset Chat Conversations ──────────────────────────────
export const sampleConversations: ChatConversation[] = [
  {
    id: "conv-1",
    title: "Why did profit drop last week?",
    messages: [
      { id: "1", role: "user", content: "Why did profit drop last week?", timestamp: "10:00 AM" },
    ],
    createdAt: "2024-10-15",
    updatedAt: "2024-10-15",
  },
  {
    id: "conv-2",
    title: "What products are losing money?",
    messages: [
      { id: "1", role: "user", content: "What products are losing money?", timestamp: "Yesterday" },
    ],
    createdAt: "2024-10-14",
    updatedAt: "2024-10-14",
  },
];

export const suggestedQuestions = [
  "Why did profit drop last week?",
  "What products are losing money?",
  "Which products should I scale?",
  "Forecast revenue for next month",
];

// ─── Ad Campaigns ───────────────────────────────────────────
export const adCampaigns: AdCampaign[] = [
  {
    id: "CAM001",
    name: "Meta Ads — Serum Broad",
    platform: "meta",
    status: "active",
    spend: 45000,
    impressions: 420000,
    clicks: 12500,
    conversions: 350,
    revenue: 189000,
    roas: 4.2,
    cpa: 128.57,
  },
  {
    id: "CAM002",
    name: "Google Ads — Search Vitamin C",
    platform: "google",
    status: "active",
    spend: 32000,
    impressions: 180000,
    clicks: 9800,
    conversions: 180,
    revenue: 112000,
    roas: 3.5,
    cpa: 177.78,
  },
  {
    id: "CAM003",
    name: "Meta Ads — Hair Oil Video",
    platform: "meta",
    status: "active",
    spend: 28000,
    impressions: 310000,
    clicks: 8900,
    conversions: 198,
    revenue: 88902,
    roas: 3.18,
    cpa: 141.41,
  },
  {
    id: "CAM004",
    name: "Google Ads — Shopping Earbuds",
    platform: "google",
    status: "paused",
    spend: 28000,
    impressions: 150000,
    clicks: 6000,
    conversions: 92,
    revenue: 229908,
    roas: 8.21,
    cpa: 304.35,
  },
];

// ─── Payment Settlements ────────────────────────────────────
export const paymentSettlements: PaymentSettlement[] = [
  {
    id: "SET001",
    gateway: "Razorpay",
    amount: 485000,
    fees: 9700,
    netAmount: 475300,
    date: "2024-10-15",
    status: "settled",
    method: "UPI",
  },
  {
    id: "SET002",
    gateway: "Razorpay",
    amount: 320000,
    fees: 7040,
    netAmount: 312960,
    date: "2024-10-14",
    status: "settled",
    method: "Credit Card",
  },
  {
    id: "SET003",
    gateway: "Cashfree",
    amount: 180000,
    fees: 3240,
    netAmount: 176760,
    date: "2024-10-14",
    status: "settled",
    method: "Net Banking",
  },
  {
    id: "SET004",
    gateway: "Razorpay",
    amount: 290000,
    fees: 5800,
    netAmount: 284200,
    date: "2024-10-13",
    status: "processing",
    method: "UPI",
  },
  {
    id: "SET005",
    gateway: "Cashfree",
    amount: 145000,
    fees: 2610,
    netAmount: 142390,
    date: "2024-10-13",
    status: "pending",
    method: "Debit Card",
  },
];

// ─── Forecast Data ──────────────────────────────────────────
export const forecastData: ForecastDataPoint[] = [
  { month: "Jul", actual: 2420000, predicted: 2420000, lower: 2420000, upper: 2420000 },
  { month: "Aug", actual: 2650000, predicted: 2600000, lower: 2600000, upper: 2600000 },
  { month: "Sep", actual: 2780000, predicted: 2750000, lower: 2750000, upper: 2750000 },
  { month: "Oct", actual: 2847500, predicted: 2900000, lower: 2900000, upper: 2900000 },
  { month: "Nov", predicted: 3150000, lower: 2850000, upper: 3450000 },
  { month: "Dec", predicted: 3600000, lower: 3100000, upper: 4100000 },
  { month: "Jan", predicted: 3200000, lower: 2650000, upper: 3750000 },
  { month: "Feb", predicted: 3350000, lower: 2700000, upper: 4000000 },
  { month: "Mar", predicted: 3500000, lower: 2750000, upper: 4250000 },
];

// ─── Team Members ───────────────────────────────────────────
export const teamMembers: TeamMember[] = [
  {
    id: "USR001",
    name: "Hari Krishna",
    email: "hari@commerceos.ai",
    role: "owner",
    lastActive: "Just now",
    status: "active",
  },
  {
    id: "USR002",
    name: "Aisha Khan",
    email: "aisha@commerceos.ai",
    role: "admin",
    lastActive: "2 mins ago",
    status: "active",
  },
  {
    id: "USR003",
    name: "Ravi Iyer",
    email: "ravi@commerceos.ai",
    role: "viewer",
    lastActive: "1 day ago",
    status: "active",
  },
];

// ─── Pricing Plans ──────────────────────────────────────────
export const pricingPlans: PricingPlan[] = [
  {
    name: "Starter",
    price: 4599,
    period: "/month",
    description: "Perfect for new D2C brands starting their profit journey.",
    features: [
      "1 Shopify Store connection",
      "Meta Ads sync (1 account)",
      "Daily profit reporting",
      "AI chat query support (100/mo)",
      "2 Team members limit",
    ],
    cta: "Start Starter Free",
    popular: false,
    gradient: "from-blue-500 to-indigo-500",
  },
  {
    name: "Growth",
    price: 8599,
    period: "/month",
    description: "The sweet spot for growing brands that need robust AI CFO tools.",
    features: [
      "Up to 3 Shopify Store connections",
      "Meta & Google Ads sync (Unlimited)",
      "Razorpay & Shiprocket sync",
      "Hourly profit reporting",
      "Unlimited AI Chat Copilot",
      "5 Team members limit",
      "Revenue forecasting reports",
    ],
    cta: "Start Growth Free",
    popular: true,
    gradient: "from-primary to-accent",
  },
  {
    name: "Scale",
    price: 21599,
    period: "/month",
    description: "Complete custom setup, high volumes, and priority AI modules.",
    features: [
      "Unlimited store connections",
      "Custom warehouse integration",
      "Real-time profit tracking",
      "Dedicated account managers",
      "Custom AI models & insights",
      "Unlimited team members",
      "Gateway settlement delay alerts",
    ],
    cta: "Contact Sales",
    popular: false,
    gradient: "from-purple-500 to-pink-500",
  },
];

// ─── Navigation Items ────────────────────────────────────────
export const navigationItems: NavItem[] = [
  { label: "Dashboard", href: "/dashboard", icon: "LayoutDashboard" },
  { label: "Orders", href: "/dashboard/orders", icon: "ShoppingCart" },
  { label: "Products", href: "/dashboard/products", icon: "Package" },
  { label: "Product Costs", href: "/dashboard/costs", icon: "Coins" },
  { label: "Customers", href: "/dashboard/customers", icon: "Users" },
  { label: "Analytics", href: "/dashboard/analytics", icon: "BarChart3" },
  { label: "Integrations", href: "/dashboard/integrations", icon: "Plug" },
  { label: "AI Chat", href: "/dashboard/ai", icon: "Bot", badge: "AI" },
  { label: "Ad Spend", href: "/dashboard/ads", icon: "Megaphone" },
  { label: "Shipping", href: "/dashboard/shipping", icon: "Truck" },
  { label: "Payments", href: "/dashboard/payments", icon: "CreditCard" },
  { label: "Forecasting", href: "/dashboard/forecasting", icon: "TrendingUp" },
  { label: "Data Export", href: "/dashboard/export", icon: "Download" },
  { label: "Settings", href: "/dashboard/settings", icon: "Settings" },
];

// ─── Shipping Metrics ────────────────────────────────────────
export const shippingMetrics = {
  totalShipments: 1180,
  delivered: 1020,
  inTransit: 98,
  rtoCount: 62,
  rtoRate: 5.3,
  avgCost: 72,
  avgDeliveryDays: 4.2,
  courierBreakdown: [
    { courier: "Delhivery", shipments: 480, avgDays: 3.8, rtoRate: 4.2 },
    { courier: "Blue Dart", shipments: 320, avgDays: 3.5, rtoRate: 3.8 },
    { courier: "DTDC", shipments: 220, avgDays: 5.1, rtoRate: 7.2 },
    { courier: "Ecom Express", shipments: 160, avgDays: 4.8, rtoRate: 6.5 },
  ],
  monthlyCosts: [
    { month: "May", cost: 72000 },
    { month: "Jun", cost: 85000 },
    { month: "Jul", cost: 78000 },
    { month: "Aug", cost: 92000 },
    { month: "Sep", cost: 88000 },
    { month: "Oct", cost: 95000 },
  ],
};

// ─── Payment Analytics ───────────────────────────────────────
export const paymentAnalytics = {
  totalProcessed: 2847500,
  totalFees: 56950,
  feePercentage: 2.0,
  methodBreakdown: [
    { method: "UPI", percentage: 42, amount: 1195950, fees: 11960 },
    { method: "Credit Card", percentage: 22, amount: 626450, fees: 13782 },
    { method: "Debit Card", percentage: 15, amount: 427125, fees: 6407 },
    { method: "Net Banking", percentage: 8, amount: 227800, fees: 5695 },
    { method: "COD", percentage: 13, amount: 370175, fees: 19162 },
  ],
};
